version: "2"
name: chat-app-backend

services:
  messaging-service:
    build: ./messaging-service
    image: ghcr.io/merosya/chat-app-backend/messaging-service:latest
    container_name: messaging-service
    restart: unless-stopped
    expose:
      - 3001
    depends_on:
      - message-db
    env_file:
      - ./messaging-service/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    links:
      - message-db:mongo
    
  message-db:
    image: mongo
    container_name: message-database
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - ~/chat-app/mongo/data/messages:/data/db
  
  auth-service:
    build: ./auth-service
    image: ghcr.io/merosya/chat-app-backend/auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    expose:
      - 3001
    depends_on:
      - auth-db
    env_file:
      - ./messaging-service/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    links:
      - auth-db:mongo
    
  auth-db:
    image: mongo
    container_name: auth-database
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - ~/chat-app/mongo/data/auth_info:/data/db

  nginx:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    depends_on:
      - messaging-service
      - auth-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/merosya.crt:/etc/ssl/merosya.crt
      - ./nginx/merosya.key:/etc/ssl/merosya.key
