name: Publish artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
          name: docker-compose
          path: docker-compose.yml
